CREATE TABLE IF NOT EXISTS "users" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "email" VARCHAR(100) NOT NULL UNIQUE,
    "password_hash" VARCHAR(255) NOT NULL,
    "email_verified" BOOLEAN NOT NULL DEFAULT FALSE,
    "verification_code" VARCHAR(6),
    "verification_code_expiry" TIMESTAMP,
    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS user_favorites (
                                              user_id BIGINT NOT NULL,
                                              recipe_id BIGINT NOT NULL,
                                              created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, recipe_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (recipe_id) REFERENCES recipes(id) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS search_history (
                                              id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                              user_id BIGINT NOT NULL,
                                              ingredients JSONB NOT NULL,
                                              created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS "recipes" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title" VARCHAR(255) NOT NULL,
    "slug" VARCHAR(255) UNIQUE,
    "description" TEXT,
    "image_url" VARCHAR(255),
    "content_json" JSONB NOT NULL,
    "prep_time_minutes" INTEGER,
    "calories" INTEGER,
    "protein" INTEGER,
    "fat" INTEGER,
    "carbohydrates" INTEGER,
    "source_url" VARCHAR(500) UNIQUE,
    PRIMARY KEY("id")
    );

CREATE TABLE IF NOT EXISTS "recipe_components" (
                                                   "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                                   "ingredient_id" BIGINT NOT NULL,
                                                   "recipe_id" BIGINT NOT NULL,
                                                   "count" DOUBLE PRECISION,
                                                   "measurement" VARCHAR(5),
    PRIMARY KEY("id")
    );

CREATE TABLE IF NOT EXISTS "favourite_recipes" (
                                                   "user_id" BIGINT NOT NULL,
                                                   "recipe_id" BIGINT NOT NULL,
                                                   PRIMARY KEY ("user_id", "recipe_id")
    );

CREATE TABLE IF NOT EXISTS "ingredients" (
                                             "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                             "name" VARCHAR(100) NOT NULL UNIQUE,
    PRIMARY KEY("id")
    );

CREATE INDEX "recipe_components_index" ON "recipe_components" ("ingredient_id");
CREATE INDEX "recipe_components_index_1" ON "recipe_components" ("recipe_id");
CREATE INDEX "favourite_recipes_index_0" ON "favourite_recipes" ("recipe_id");
CREATE INDEX "favourite_recipes_index_1" ON "favourite_recipes" ("user_id");
CREATE UNIQUE INDEX "ingredients_index_0" ON "ingredients" ("name");

CREATE INDEX IF NOT EXISTS idx_user_favorites_user ON user_favorites(user_id);
CREATE INDEX IF NOT EXISTS idx_search_history_user ON search_history(user_id);
CREATE INDEX IF NOT EXISTS idx_search_history_created ON search_history(user_id, created_at DESC);

ALTER TABLE "favourite_recipes"
    ADD FOREIGN KEY("user_id") REFERENCES "users"("id")
        ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "favourite_recipes"
    ADD FOREIGN KEY("recipe_id") REFERENCES "recipes"("id")
        ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "recipe_components"
    ADD FOREIGN KEY("ingredient_id") REFERENCES "ingredients"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "recipe_components"
    ADD FOREIGN KEY("recipe_id") REFERENCES "recipes"("id")
        ON UPDATE NO ACTION ON DELETE CASCADE;