CREATE TABLE IF NOT EXISTS "users" (
                                       "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                       "login" VARCHAR(50) NOT NULL UNIQUE,
    "password_hash" VARCHAR(255) NOT NULL,
    PRIMARY KEY("id")
    );




CREATE TABLE IF NOT EXISTS "recipes" (
                                         "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                         "title" VARCHAR(255) NOT NULL,
    "description" TEXT,
    "image_url" VARCHAR(255),
    "content_json" JSONB NOT NULL,
    "prep_time_minutes" INTEGER,
    "calories" INTEGER,
    "protein" INTEGER,
    "fat" INTEGER,
    "carbohydrates" INTEGER,
    "source_url" VARCHAR(500) UNIQUE,
    PRIMARY KEY("id")
    );


CREATE INDEX "recipes_index_0"
    ON "recipes" ("calories");
CREATE INDEX "recipes_index_1"
    ON "recipes" ("prep_time_minutes");

CREATE TABLE IF NOT EXISTS "recipe_components" (
                                                   "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                                   "ingredient_id" INTEGER NOT NULL,
                                                   "recipe_id" INTEGER NOT NULL,
                                                   "count" DOUBLE PRECISION,
                                                   "measurement" VARCHAR(5),
    PRIMARY KEY("id")
    );


CREATE INDEX "recipe_components_index"
    ON "recipe_components" ("ingredient_id");
CREATE INDEX "recipe_components_index_1"
    ON "recipe_components" ("recipe_id");

CREATE TABLE IF NOT EXISTS "favourite_recipes" (
                                                   "user_id" INTEGER NOT NULL,
                                                   "recipe_id" INTEGER NOT NULL,
                                                   PRIMARY KEY ("user_id", "recipe_id")
    );


CREATE INDEX "favourite_recipes_index_0"
    ON "favourite_recipes" ("recipe_id");
CREATE INDEX "favourite_recipes_index_1"
    ON "favourite_recipes" ("user_id");

CREATE TABLE IF NOT EXISTS "ingredients" (
                                             "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                             "name" VARCHAR(100) NOT NULL UNIQUE,
    PRIMARY KEY("id")
    );


CREATE UNIQUE INDEX "ingredients_index_0"
    ON "ingredients" ("name");
ALTER TABLE "favourite_recipes"
    ADD FOREIGN KEY("user_id") REFERENCES "users"("id")
        ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "favourite_recipes"
    ADD FOREIGN KEY("recipe_id") REFERENCES "recipes"("id")
        ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "recipe_components"
    ADD FOREIGN KEY("ingredient_id") REFERENCES "ingredients"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "recipe_components"
    ADD FOREIGN KEY("recipe_id") REFERENCES "recipes"("id")
        ON UPDATE NO ACTION ON DELETE CASCADE;